### ISSUE TITLE
English translation

### ISSUE THREAD

**Issue by SimonBard** [edsonsbj/Backup_Restore_Rsync#2]
Many thanks for the script. 

It would be really useful to have an English translation, p.ex. by deepl. 

```
Backup and Restore Scripts using Rsync

Backup and restore scripts that use rsync and tar as a way to backup and restore your files and settings.

These scripts assume that you will be backing up your files to external media with a large amount of space to store your backups.

Backing Up

    Install Git if it is not already installed.
    Clone this git clone Repository, or download and unzip the zip file.
    Copy the backup.sh Configs and include-lst files to a folder of your choice.
    Change the variables in the Configs file to suit your needs.
    Add the path to the Configs file in the backup.sh and restore.sh scripts in the CONFIG="/Path/to/Nextcloud-Backup-Restore/Configs" part.
    Go to the folder where you placed the scripts and make them executable with the command sudo chmod a+x.
    Run the backup: sudo /path/to/backup.sh.
    Schedule the backup in Cron: 00 00** * sudo /path/to/backup.sh

Restore

    Edit the backup.sh with your favorite editor and where "$DIR01" "$DESTINATIONDIR" and change it to the following "$DESTINATIONDIR" "$DIR01".

Backup & Restore Nextcloud Servers

This script performs Backup and Restore of a Nextcloud server installed via snap

Performing the Backup

    Install Git if it is not already installed.
    Clone this git clone Repository, or download and unzip the zip file.
    Copy the files from the Nextcloud folder to a folder of your choice.
    Change the variables in the Configs file according to your needs.
    Do not change the NEXTCLOUD_CONFIG and TAR_NEXTCLOUD_CONFIG variables in your Configs file
    Add the path to the Configs file in the backup.sh and restore.sh scripts in the CONFIG="/Path/to/Nextcloud-Backup-Restore/Configs" part.
    Include the files that you do not want to backup in your ./Nextcloud/data folder in the exclude-lst file. If you intend to backup only certain folders or users, include them in the include-lst file and change the command in the script from --exclude-from to --files-from.
    Make the backup.sh. and restore.sh. scripts executable

Performing a Restore

    Make sure your distribution already has snap support enabled, if not.
    install the nextcloud snap.
    Run the restore.sh. script.

```

**Comment by edsonsbj** [comment]
> Many thanks for the script.
> 
> It would be really useful to have an English translation, p.ex. by deepl.
> 
> ```
> Backup and Restore Scripts using Rsync
> 
> Backup and restore scripts that use rsync and tar as a way to backup and restore your files and settings.
> 
> These scripts assume that you will be backing up your files to external media with a large amount of space to store your backups.
> 
> Backing Up
> 
>     Install Git if it is not already installed.
>     Clone this git clone Repository, or download and unzip the zip file.
>     Copy the backup.sh Configs and include-lst files to a folder of your choice.
>     Change the variables in the Configs file to suit your needs.
>     Add the path to the Configs file in the backup.sh and restore.sh scripts in the CONFIG="/Path/to/Nextcloud-Backup-Restore/Configs" part.
>     Go to the folder where you placed the scripts and make them executable with the command sudo chmod a+x.
>     Run the backup: sudo /path/to/backup.sh.
>     Schedule the backup in Cron: 00 00** * sudo /path/to/backup.sh
> 
> Restore
> 
>     Edit the backup.sh with your favorite editor and where "$DIR01" "$DESTINATIONDIR" and change it to the following "$DESTINATIONDIR" "$DIR01".
> 
> Backup & Restore Nextcloud Servers
> 
> This script performs Backup and Restore of a Nextcloud server installed via snap
> 
> Performing the Backup
> 
>     Install Git if it is not already installed.
>     Clone this git clone Repository, or download and unzip the zip file.
>     Copy the files from the Nextcloud folder to a folder of your choice.
>     Change the variables in the Configs file according to your needs.
>     Do not change the NEXTCLOUD_CONFIG and TAR_NEXTCLOUD_CONFIG variables in your Configs file
>     Add the path to the Configs file in the backup.sh and restore.sh scripts in the CONFIG="/Path/to/Nextcloud-Backup-Restore/Configs" part.
>     Include the files that you do not want to backup in your ./Nextcloud/data folder in the exclude-lst file. If you intend to backup only certain folders or users, include them in the include-lst file and change the command in the script from --exclude-from to --files-from.
>     Make the backup.sh. and restore.sh. scripts executable
> 
> Performing a Restore
> 
>     Make sure your distribution already has snap support enabled, if not.
>     install the nextcloud snap.
>     Run the restore.sh. script.
> ```

Hi Friend!!

Already I made the translation see if it was good anything I'm available.

**Comment by edsonsbj** [comment]
> Many thanks for the script.
> 
> It would be really useful to have an English translation, p.ex. by deepl.
> 
> ```
> Backup and Restore Scripts using Rsync
> 
> Backup and restore scripts that use rsync and tar as a way to backup and restore your files and settings.
> 
> These scripts assume that you will be backing up your files to external media with a large amount of space to store your backups.
> 
> Backing Up
> 
>     Install Git if it is not already installed.
>     Clone this git clone Repository, or download and unzip the zip file.
>     Copy the backup.sh Configs and include-lst files to a folder of your choice.
>     Change the variables in the Configs file to suit your needs.
>     Add the path to the Configs file in the backup.sh and restore.sh scripts in the CONFIG="/Path/to/Nextcloud-Backup-Restore/Configs" part.
>     Go to the folder where you placed the scripts and make them executable with the command sudo chmod a+x.
>     Run the backup: sudo /path/to/backup.sh.
>     Schedule the backup in Cron: 00 00** * sudo /path/to/backup.sh
> 
> Restore
> 
>     Edit the backup.sh with your favorite editor and where "$DIR01" "$DESTINATIONDIR" and change it to the following "$DESTINATIONDIR" "$DIR01".
> 
> Backup & Restore Nextcloud Servers
> 
> This script performs Backup and Restore of a Nextcloud server installed via snap
> 
> Performing the Backup
> 
>     Install Git if it is not already installed.
>     Clone this git clone Repository, or download and unzip the zip file.
>     Copy the files from the Nextcloud folder to a folder of your choice.
>     Change the variables in the Configs file according to your needs.
>     Do not change the NEXTCLOUD_CONFIG and TAR_NEXTCLOUD_CONFIG variables in your Configs file
>     Add the path to the Configs file in the backup.sh and restore.sh scripts in the CONFIG="/Path/to/Nextcloud-Backup-Restore/Configs" part.
>     Include the files that you do not want to backup in your ./Nextcloud/data folder in the exclude-lst file. If you intend to backup only certain folders or users, include them in the include-lst file and change the command in the script from --exclude-from to --files-from.
>     Make the backup.sh. and restore.sh. scripts executable
> 
> Performing a Restore
> 
>     Make sure your distribution already has snap support enabled, if not.
>     install the nextcloud snap.
>     Run the restore.sh. script.
> ```

Hi Friend!!

Already I made the translation see if it was good anything I'm available.
